-- SQL for creating the sales_data table in Supabase
-- Run this in your Supabase SQL Editor

CREATE TABLE IF NOT EXISTS public.sales_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data JSONB NOT NULL,
    filename TEXT,
    record_count INT4,
    user_id UUID REFERENCES auth.users(id), -- Optional: Link to Supabase Auth users
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.sales_data ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows users to see only their own data
-- (Note: This assumes you use the user_id column)
CREATE POLICY "Users can only access their own sales data" 
ON public.sales_data 
FOR ALL 
USING (auth.uid() = user_id);

-- Create a policy for anonymous access if needed (optional)
-- CREATE POLICY "Allow anonymous inserts" ON public.sales_data FOR INSERT WITH CHECK (true);
