-- SQL for creating the required tables in Supabase
-- Run this in your Supabase SQL Editor

-- =============================================
-- USERS TABLE
-- =============================================
CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT UNIQUE NOT NULL,
    full_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view and update their own profile"
ON public.users
FOR ALL
USING (auth.uid() = id);

-- =============================================
-- SALES DATA TABLE
-- =============================================
CREATE TABLE IF NOT EXISTS public.sales_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data JSONB NOT NULL,
    filename TEXT,
    record_count INT4,
    user_id UUID REFERENCES auth.users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.sales_data ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can only access their own sales data"
ON public.sales_data
FOR ALL
USING (auth.uid() = user_id);

-- =============================================
-- FORECASTS TABLE
-- =============================================
CREATE TABLE IF NOT EXISTS public.forecasts (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id),
    column TEXT NOT NULL,
    horizon INT4 NOT NULL,
    model TEXT NOT NULL DEFAULT 'sarima',
    forecast_data JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.forecasts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can only access their own forecasts"
ON public.forecasts
FOR ALL
USING (auth.uid() = user_id);
